"""Common generation parsing, sizing, and output helpers."""

from app.legacy import (
    api_headers,
    apimart_size_resolution,
    aspect_ratio_value,
    compress_data_url_image,
    extract_generic_image,
    extract_image,
    extract_task_id,
    gpt_image_2_request_size,
    gpt_image_2_target_size,
    image_payload_from_data_url,
    image_payload_from_text,
    image_size_context,
    image_task_failure_reason,
    image_task_status,
    images_api_unsupported,
    is_apimart_provider,
    is_gpt_image_2_model,
    is_mindapi_provider,
    is_nano_banana_model,
    modelscope_image_url,
    normalize_ai_image_to_size,
    normalize_gpt_image_2_size,
    normalize_image_aspect_ratio,
    normalize_image_resolution,
    parse_size_pair,
    reference_to_data_url,
    save_ai_image_to_output,
    save_remote_video_to_output,
    selected_model,
    safe_upstream_summary,
    unwrap_apimart_response,
)
