from fastapi import APIRouter
from app.services import canvas_service as service

router = APIRouter()

router.post('/api/canvas-image-tasks')(service.create_canvas_image_task)
router.get('/api/canvas-image-tasks/{task_id}')(service.get_canvas_image_task)
router.post('/api/canvas-video')(service.canvas_video)
router.post('/api/canvas-llm')(service.canvas_llm)
router.get('/api/conversations')(service.conversations)
router.post('/api/conversations')(service.create_conversation)
router.get('/api/conversations/{conversation_id}')(service.get_conversation)
router.delete('/api/conversations/{conversation_id}')(service.delete_conversation)
router.get('/api/canvases')(service.canvases)
router.get('/api/canvases/trash')(service.trashed_canvases)
router.post('/api/canvases')(service.create_canvas)
router.get('/api/canvases/{canvas_id}/meta')(service.get_canvas_meta)
router.get('/api/canvases/{canvas_id}')(service.get_canvas)
router.post('/api/canvas-assets/check')(service.check_canvas_assets)
router.post('/api/canvas-assets/download')(service.download_canvas_assets)
router.post('/api/canvas-media/upload')(service.upload_canvas_media)
router.get('/api/asset-library')(service.get_asset_library)
router.post('/api/asset-library/categories')(service.create_asset_library_category)
router.patch('/api/asset-library/categories/{category_id}')(service.rename_asset_library_category)
router.delete('/api/asset-library/categories/{category_id}')(service.delete_asset_library_category)
router.post('/api/asset-library/items')(service.add_asset_library_item)
router.patch('/api/asset-library/items/{item_id}')(service.rename_asset_library_item)
router.delete('/api/asset-library/items/{item_id}')(service.delete_asset_library_item)
router.put('/api/canvases/{canvas_id}')(service.update_canvas)
router.delete('/api/canvases/{canvas_id}')(service.delete_canvas)
router.post('/api/canvases/{canvas_id}/restore')(service.restore_canvas)
router.delete('/api/canvases/{canvas_id}/purge')(service.purge_canvas)
router.post('/api/chat')(service.chat)
router.post('/api/chat/stream')(service.chat_stream)
